config/routes.rb
DemoApp::Application.routes.draw do
  resources :transfer_1hs

  resources :transfers

  resources :agents

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  include TransferAssociations
  include TransferValidations

  # I don't want to put it in separate method so there
  after_create :aggregate

  # i don't want to hack the relations so i just put it like method
  def relevant_aggregated_transfer
    Transfer1h.find_by_transfer self
  end

  private
  def aggregate
    ::Transfer1h.aggregate(self)
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transfer }
      else
        format.html { render action: 'new' }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:id, :sender_id, :reciever_id, :ammount, :payout, :transfered_at)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for(@transfer) do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :reciever_id %><br>
    <%= f.number_field :reciever_id %>
  </div>
  <div class="field">
    <%= f.label :ammount %><br>
    <%= f.text_field :ammount %>
  </div>
  <div class="field">
    <%= f.label :payout %><br>
    <%= f.text_field :payout %>
  </div>
  <div class="field">
    <%= f.label :transfered_at %><br>
    <%= f.datetime_select :transfered_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing transfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<h1>Listing transfers</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Sender</th>
      <th>Reciever</th>
      <th>Ammount</th>
      <th>Payout</th>
      <th>Transfered at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.id %></td>
        <td><%= transfer.sender_id %></td>
        <td><%= transfer.reciever_id %></td>
        <td><%= transfer.ammount %></td>
        <td><%= transfer.payout %></td>
        <td><%= transfer.transfered_at %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @transfer.id %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @transfer.sender_id %>
</p>

<p>
  <strong>Reciever:</strong>
  <%= @transfer.reciever_id %>
</p>

<p>
  <strong>Ammount:</strong>
  <%= @transfer.ammount %>
</p>

<p>
  <strong>Payout:</strong>
  <%= @transfer.payout %>
</p>

<p>
  <strong>Transfered at:</strong>
  <%= @transfer.transfered_at %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>